version: '3.9'

services:
  proxer:
    build:  
      context: ./
      dockerfile: Dockerfile
    container_name: proxer
    restart: on-failure
    ports:
      - ${PROXER_PORT:-8080}:8080
    environment:
      http_proxy=${HTTP_PROXER}
      https_proxy=${HTTPS_PROXER}